### PR TITLE
Zipped

### PR DESCRIPTION
**Pull request by PhelypeOleinik**
`dvipdfmx` no longer supports compressed graphics (https://tug.org/pipermail/dvipdfmx/2021-March/000252.html), so this PR changes the graphics inclusion rule in `xetex.def` and `dvipdfmx.def` from `eps` to a new rule `zipped` that doesn't include the file and raises an error instead.

### CODE REVIEW

**Comment by josephwright** [comment]
Looks good to me

**Comment by josephwright** [comment]
Would it be best to put in a parallel PR for the `graphics` bundle just dropping the entire thing?

**Comment by PhelypeOleinik** [comment]
You mean dropping all the tests for `.gz` in `graphics.sty`?  I don't think so, because zipped graphics still work in dvips

**Comment by josephwright** [comment]
> You mean dropping all the tests for `.gz` in `graphics.sty`? I don't think so, because zipped graphics still work in dvips

I meant in the documentation part: as it only works with one backend, I don't feel we should advertise it.

**Comment by PhelypeOleinik** [comment]
Ah, the documentation, yes.  I was talking to David earlier about how to best (un)document this part.  I'll tackle that later

**Review by davidcarlisle — COMMENTED** [review]
This is OK I think but I wonder if it might be simpler to understand if you simply deleted the rules (which I don't think ever worked) and allow the standard unknown graphics extension error (as you would get from luatex or pdftex say)

**Comment by PhelypeOleinik** [comment]
That would be simpler, yes, but @u-fischer and I thought it would be less clear, especially because it's something that worked (a _long_ time ago) and now it doesn't. Though admittedly you can count on one fingers of hand the number of people using that :)

So I don't know... Simpler should suffice too

**Comment by davidcarlisle** [comment]
I would drop it, the list of supported extensions is explicitly specific to each back end, and if dvips is the only one supporting eps.gz then that's the way it is. I think an unknown extension error is fine rather than a custom error message.

**Pull request merged**
